# Generated by Django 4.1.4 on 2022-12-31 18:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annonces', '0003_alter_annonce_datepub_alter_deposer_datepub'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='datepub',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 19, 59, 27, 615013)),
        ),
        migrations.DeleteModel(
            name='Deposer',
        ),
    ]
