# Generated by Django 4.1.4 on 2022-12-31 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0004_annonce_user_alter_annonce_datepub_delete_deposer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='datepub',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 21, 24, 33, 745398)),
        ),
    ]
