# Generated by Django 4.1.4 on 2023-01-02 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0007_alter_annonce_datepub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='datepub',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 15, 57, 33, 108273)),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='photoAnnonce',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
