# Generated by Django 4.1.4 on 2023-01-02 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0008_alter_annonce_datepub_alter_annonce_photoannonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='datepub',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 2, 19, 5, 21, 937830), null=True),
        ),
    ]
