# Generated by Django 4.1.4 on 2023-01-02 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0009_alter_annonce_datepub'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='date2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='datepub',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 2, 19, 44, 2, 829201), null=True),
        ),
    ]
