# Generated by Django 4.1.4 on 2023-01-02 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0010_annonce_date1_annonce_date2_alter_annonce_datepub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='date2',
        ),
        migrations.AlterField(
            model_name='annonce',
            name='datepub',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 2, 19, 46, 14, 416701), null=True),
        ),
    ]
