# Generated by Django 4.1.4 on 2023-01-27 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0013_alter_annonce_communeannonce_alter_annonce_datepub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='datepub',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 27, 18, 10, 34, 290327), null=True),
        ),
    ]
