# Generated by Django 4.1.4 on 2023-01-27 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0014_alter_annonce_datepub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='communeAnnonce',
            field=models.CharField(choices=[('1-Adrar', (('01001-Adrar', '01001-Adrar'), ('01002-Tamest', '01002-Tamest'), ('01003-Charouine', '01003-Charouine'), ('01004-Reggane', '01004-Reggane'), ('01005-Inozghmir', '01005-Inozghmir'), ('01006-Tit', '01006-Tit'), ('01007-Ksar Kaddour', '01007-Ksar Kaddour'), ('01008-Tsabit', '01008-Tsabit'), ('01009-Timimoun', '01009-Timimoun'), ('01010-Ouled Said', '01010-Ouled Said'), ('01011-Zaouiet', '01011-Zaouiet'), ('01012-Aoulef', '01012-Aoulef'), ('01013-Timokten', '01013-Timokten'), ('01014-Tamentit', '01014-Tamentit'), ('01015-Fenoughil', '01015-Fenoughil'), ('01016-Tinerkouk', '01016-Tinerkouk'), ('01017-Deldoul', '01017-Deldoul'), ('01018-Sali', '01018-Sali'), ('01019-Akabli', '01019-Akabli'), ('01020-Metarfa', '01020-Metarfa'), ('01021-O Ahmed Timmi', '01021-O Ahmed Timmi'), ('01022-Bouda', '01022-Bouda'), ('01023-Aougrout', '01023-Aougrout'), ('01024-Talmine', '01024-Talmine'), ('01025-B Badji Mokhtar', '01025-B Badji Mokhtar'), ('01026-Sbaa', '01026-Sbaa'), ('01027-Ouled Aissa', '01027-Ouled Aissa'), ('01028-Timiaouine', '01028-Timiaouine'))), ('2-Chelf', (('"02001-Chelf', '"02001-Chelf'), ('02002-Tenes', '02002-Tenes'), ('02003-Benairia', '02003-Benairia'), ('02004-El Karimia', '02004-El Karimia'), ('02005-Tadjna', '02005-Tadjna'), ('02006-Taougrite', '02006-Taougrite'), ('02007-Beni Haoua', '02007-Beni Haoua'), ('02008-Sobha', '02008-Sobha'), ('02009-Harchoun', '02009-Harchoun'), ('02010-Ouled Fares', '02010-Ouled Fares'), ('02011-Sidi Akacha', '02011-Sidi Akacha'), ('02012-Boukadir', '02012-Boukadir'), ('02013-Sidi Rached', '02013-Sidi Rached'), ('02014-Talassa', '02014-Talassa'), ('02015-Herenfa', '02015-Herenfa'), ('02016-Ouled Goussine', '02016-Ouled Goussine'), ('02017-Dahra', '02017-Dahra'), ('02018-Ouled Abbes', '02018-Ouled Abbes'), ('02019-Sendjas', '02019-Sendjas'), ('02020-Zeboudja', '02020-Zeboudja'), ('02021-Ouled Sly', '02021-Ouled Sly'), ('02022-Abou El Hassen', '02022-Abou El Hassen'), ('02023-El Marsa', '02023-El Marsa'), ('02024-Chettia', '02024-Chettia'), ('02025-Sidi Abderrahmane', '02025-Sidi Abderrahmane'), ('02026-Moussadek', '02026-Moussadek'), ('02027-El Hadjadj', '02027-El Hadjadj'), ('02028-Labiod Medjadja', '02028-Labiod Medjadja'), ('02029-Oued Fodda', '02029-Oued Fodda'), ('02030-Ouled Ben Abdelkader', '02030-Ouled Ben Abdelkader'), ('02031-Bouzghaia', '02031-Bouzghaia'), ('02033-Oum Drou', '02033-Oum Drou'), ('02034-Breira', '02034-Breira'), ('02035-Ben Boutaleb', '02035-Ben Boutaleb')))], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='datepub',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 27, 19, 20, 52, 371905), null=True),
        ),
    ]
